name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
      runs-on: ubuntu-latest
      steps:
        - name: Print Greeting
          run: |
            echo "Hello world" 
            echo "My name is Krishan Kumar Patel"
        - name: Print Good bye
          run: echo "Done -bye"
